# Generated by Django 5.0.6 on 2024-08-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
